spring:
  application:
    name: notification-service
  sleuth:
    sampler:
      probability: 1
    integration:
      enabled: true
  zipkin:
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.amircode.notificationservice.OrderPlacedEvent
      group-id: notificationId
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: prometheus