server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5431/order-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    bootstrap-servers: broker:29092
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka