server:
  port: 8080
spring:
  zipkin:
    base-url: http://zipkin:9411
  data:
    mongodb:
      host: mongo
      port: 27017
      database: product-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka