server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka